<!-- scripts -->
<script src="scripts/jquery-1.11.1.min.js" type="text/javascript"></script>
<script src="scripts/modernizr.min.js" type="text/javascript"></script>
<!-- jcarousel -->
<script src="scripts/jcarousel/jquery.jcarousel.min.js" type="text/javascript"></script>
<script src="scripts/jcarousel/jcarousel.responsive.js" type="text/javascript"></script>
<!-- slidLp -->
<script src="scripts/slideLp/slideLp.js" type="text/javascript"></script>
<script src="scripts/slideLp/highlight.js" type="text/javascript"></script>
<!-- cart -->
<script src="scripts/cart/cart.js" type="text/javascript"></script>
<!-- how -->
<script src="scripts/how/how.js" type="text/javascript"></script>
<!-- validation -->
<script src="scripts/meiomask/meiomask.js" type="text/javascript"></script>
<script src="scripts/meiomask/meiomask.init.js" type="text/javascript"></script>
<script src="scripts/validate/jquery.validate.js" type="text/javascript"></script>
<script src="scripts/validate/jquery.validate.init.js" type="text/javascript"></script>
<script src="scripts/validate/contact.js" type="text/javascript"></script>
<!-- utils -->
<script src="scripts/utils.js" type="text/javascript"></script>
<!-- iscroll -->
<script src="scripts/iscroll/iscroll.js" type="text/javascript"></script>
<script src="scripts/iscroll/scroll.js" type="text/javascript"></script>
